package:
  name: paramnb
  version: 1.0.2

source:
  path: .

extra:
  channels:
    - ioam
    - conda-forge

requirements:
  build:
    - python
    - setuptools
    - param >=1.4.1
    - ipywidgets >=5.2.2
  run:
    - python
    - ipywidgets >=5.2.2
    - param >=1.4.1

test:
  imports:
    - paramnb

about:
  home: http://github.com/ioam/paramnb
  summary: Generate ipywidgets from Parameterized objects in the notebook
  license: BSD
